name: Test GitHub Actions
on:
  push:
    branches:
      - master
    paths:
      - folder1/**
jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "action1 is run for folder1"