name: CDK deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - cdk/**

permissions:
  id-token: write
  contents: read 

jobs:
  deploy_workflow:
    uses: Hemendra05/github-repo/.github/workflows/main.yml@dev
    with:
      path: ./cdk/
      assume_role: arn:aws:iam::872436821098:role/ExampleGithubRole