name: Test GitHub Actions For Folder1

on:
  push:
    branches: [ master ]
    paths:
      - folder1/**
  pull_request:
    branches: [ master ]
    paths:
      - folder1/**
  

jobs:
  call_main_workflow:
    uses: Hemendra05/github-repo/.github/workflows/main.yml@dev
    with:
      path: ./folder1/