# This is a basic workflow to help you get started with Actions

name: Test GitHub Actions For Folder2

on:
  push:
    branches: [ master ]
    paths:
      - folder2/**
  pull_request:
    branches: [ master ]
    paths:
      - folder2/**

jobs:
  call_main_workflow:
    uses: ./.github/workflows/main.yml@main
    with:
      path: ./folder2/