name: Test GitHub Actions For Folder1

on:
  push:
    branches: [ master ]
    paths:
      - folder1/**
  

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: |
      #     echo Hello, folder!,
      #     node --version

    container: hemendra05/node

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          echo Hello, Container!,
          python --version

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
