name: Test GitHub Actions For Folder1

on:
  push:
    branches: [ master ]
    paths:
      - folder1/**
  pull_request:
    branches: [ master ]
    paths:
      - folder1/**
  

jobs:
  run_linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true

  bandit_check:
    runs-on: ubuntu-latest
    container: python:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Bandit Library
        run: |
          pip install bandit

      - name: Check Security
        run: |
          bandit -r .

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: python --version