# This is a basic workflow to help you get started with Actions

name: Test GitHub Actions For Folder2

on:
  push:
    branches: [ master ]
    paths:
      - folder2/**
  pull_request:
    branches: [ master ]
    paths:
      - folder2/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        working-directory: ./folder2
        run: |
          npm i
          ls

      # - name: Run linters
      #   uses: wearerequired/lint-action@v1
      #   with:
      #     eslint: true
      #     prettier: true