name: Test GitHub Actions For Folder1

on:
  push:
    branches: [ master ]
    paths:
      - folder1/**
  pull_request:
    branches: [ master ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    container: hemendra05/nodejs:latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          echo Hello, Container!,
          npm i folder1/package.json

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true
