name: Main workflow for Python

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

      assume_role:
        required: true
        type: string

permissions:
  id-token: write
  contents: read 

jobs:
  run_linters:
    if: ${{ github.ref_name == 'dev1' }}
    runs-on: ubuntu-latest
    container: python:latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          black_dir: ${{ inputs.path }}
          flake8: true
          flake8_dir: ${{ inputs.path }}

  pylama_Check:
    if: ${{ github.ref == 'refs/heads/dev'' }}
    runs-on: ubuntu-latest
    container: python:latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Pylama Library
        run: |
          pwd
          ls
          pip install pylama

      - name: Check Pylama
        working-directory: ${{ inputs.path }}
        run: |
          pylama

  bandit_check:
    if: ${{ github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    container: python:latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Bandit Library
        run: |
          pip install bandit

      - name: Check Security
        working-directory: ${{ inputs.path }}
        run: |
          bandit -r .

  build:
    if: ${{ github.ref_name == 'dev1' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - run: python --version

  deploy:
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
    runs-on: ubuntu-latest
    container: hemendra05/aws-cdk
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.assume_role }}
          aws-region: ap-south-1

      - uses: actions/checkout@v2

      - name: Login into AWS CodeArtifacts
        run: aws codeartifact login --tool pip --repository cdk_base_functions --domain myways-devops --domain-owner 872436821098

      - name: Installing requirements
        working-directory: ${{ inputs.path }}
        run: pip install -r requirements.txt

      - name: Deploy the application
        working-directory: ${{ inputs.path }}
        run: cdk deploy --require-approval never